version: "3"

services:
  grpc-server:
    build:
      context: .
      dockerfile: ./grpc-server/Dockerfile
      args:
        - grpc_server_port=45310
  web-api:
    build:
      context: .
      dockerfile: ./web-api/Dockerfile
      args:
        - grpc_server_port=45310
        - grpc_server_host=grpc-server
        - flask_app=server.py
        - flask_run_port=5002
        - flask_run_host=0.0.0.0
    ports:
      - "5002:5002"
    depends_on:
      - "grpc-server"
  dashboard:
    build:
      context: ./frontend
      args:
        - web_api_port=5002
        - web_api_host=127.0.0.1
    ports:
      - "8080:80"
    depends_on:
      - "web-api"
