version: "3"

services:
  grpc-server:
    build:
      context: .
      dockerfile: ./grpc-server/Dockerfile
      args:
        - grpc_server_port=45310
    ports:
      - "45310:45310"
  web-api:
    build:
      context: .
      dockerfile: ./web-api/Dockerfile
      args:
        - flask_app=server.py
        - flask_run_port=5000
        - flask_run_host=0.0.0.0
    ports:
      - "5000:5000"
