# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import measurement_pb2 as measurement__pb2


class MeterUsageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMeterUsage = channel.unary_unary(
                '/MeterUsageService/GetMeterUsage',
                request_serializer=measurement__pb2.Empty.SerializeToString,
                response_deserializer=measurement__pb2.MeterUsage.FromString,
                )


class MeterUsageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMeterUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeterUsageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMeterUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeterUsage,
                    request_deserializer=measurement__pb2.Empty.FromString,
                    response_serializer=measurement__pb2.MeterUsage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MeterUsageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MeterUsageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMeterUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MeterUsageService/GetMeterUsage',
            measurement__pb2.Empty.SerializeToString,
            measurement__pb2.MeterUsage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
